services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    external: true
